### ISSUE TITLE
Update template for projectpanoptes.org blog

### ISSUE THREAD

**Issue by mimming** [panoptes/panoptes.github.io#5]
## Core stuff
- Depends on the blog being moved to projectpanoptes.org
- Adjust [this template](https://github.com/BlackrockDigital/startbootstrap-clean-blog-jekyll) to a dark theme, to match the rest of projectpanoptes.org
## Bonus items
- Consider adding some auto-thumbnail processing scripts, because we will probably have lots of pretty images and it'd be nice if they were compressed

**Comment by nclairesays** [comment]
Maybe update this issue? The current 2019 theme of projectpanoptes.org is now using a light colored themed template, compared to the pre-April 2018 dark colored theme.

**Comment by jgeorges** [comment]
To add to @nclairesays comment, the pre-April 2018 site can be found here: https://web.archive.org/web/20180425162545/http://www.projectpanoptes.org/index.html

**Comment by wtgee** [comment]
Thanks @nclairesays  and @jgeorges ! I think I'm just going to close this and if @mimming wants she can re-open.
